// import { projectsData } from './projectsData.js';

const projectsData = [
	{
		id: 1,
		title: 'Social network for communication in English',
        skills: 'React | Node.js | MongoDB',
        imgTab: '../image/projectsImg/tablet/img-1-tab.png',
		// img: project1,
		// imgTablet: projectTablet1,
		// imgMobile: projectMobile1,
		demoLink: 'https://dear-penfriend.netlify.app/',
		gitLink: 'https://github.com/ArtemYakushkin/dear_penfriend',
	},
	{
		id: 2,
		title: 'Burger restaurant',
		skills: 'Angular | HTML | CSS',
        imgTab: '../image/projectsImg/tablet/img-2-tab.png',
		// img: project2,
		// imgTablet: projectTablet2,
		// imgMobile: projectMobile2,
		demoLink: 'https://artemyakushkin.github.io/burgers/',
		gitLink: 'https://github.com/ArtemYakushkin/burgers',
	},
	{
		id: 3,
		title: 'Application for calculating the number of calories',
		skills: 'React | Node.js | MongoDB',
        imgTab: '../image/projectsImg/tablet/img-3-tab.png',
		// img: project3,
		// imgTablet: projectTablet3,
		// imgMobile: projectMobile3,
		demoLink: 'https://artemyakushkin.github.io/slim-mom-project-react/home',
		gitLink: 'https://github.com/ArtemYakushkin/slim-mom-project-react',
	},
	{
		id: 4,
		title: 'Image search service',
		skills: 'React | Rest API',
        imgTab: '../image/projectsImg/tablet/img-4-tab.png',
		// img: project4,
		// imgTablet: projectTablet4,
		// imgMobile: projectMobile4,
		demoLink: 'https://artemyakushkin.github.io/goit-react-hw-04-images/',
		gitLink: 'https://github.com/ArtemYakushkin/goit-react-hw-04-images/tree/main',
	},
	{
		id: 5,
		title: 'Ice cream sales website',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-5-tab.png',
		// img: project5,
		// imgTablet: projectTablet5,
		// imgMobile: projectMobile5,
		demoLink: 'https://artemyakushkin.github.io/team-project-iceCream/',
		gitLink: 'https://github.com/ArtemYakushkin/team-project-iceCream',
	},
	{
		id: 6,
		title: 'Movie search application',
		skills: 'HTML | SCSS | JavaScript | Rest API',
        imgTab: '../image/projectsImg/tablet/img-6-tab.png',
		// img: project6,
		// imgTablet: projectTablet6,
		// imgMobile: projectMobile6,
		demoLink: 'https://artemyakushkin.github.io/team-project-js-Filmoteka/',
		gitLink: 'https://github.com/ArtemYakushkin/team-project-js-Filmoteka',
	},
	{
		id: 7,
		title: 'Website for the production and sale of paper cups',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-7-tab.png',
		// img: project7,
		// imgTablet: projectTablet7,
		// imgMobile: projectMobile7,
		demoLink: 'https://artemyakushkin.github.io/paknet/',
		gitLink: 'https://github.com/ArtemYakushkin/paknet',
	},
	{
		id: 8,
		title: 'Landing site for advertising the Xiaomi Himo C26 bicycle',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-8-tab.png',
		// img: project8,
		// imgTablet: projectTablet8,
		// imgMobile: projectMobile8,
		demoLink: 'https://artemyakushkin.github.io/xiaomi-bike/#specification',
		gitLink: 'https://github.com/ArtemYakushkin/xiaomi-bike',
	},
	{
		id: 9,
		title: 'Landing site for a photo studio',
		skills: 'HTML | SCSS',
        imgTab: '../image/projectsImg/tablet/img-9-tab.png',
		// img: project9,
		// imgTablet: projectTablet9,
		// imgMobile: projectMobile9,
		demoLink: 'https://artemyakushkin.github.io/photo-studio-2/',
		gitLink: 'https://github.com/ArtemYakushkin/photo-studio-2',
	},
	{
		id: 10,
		title: 'Furniture store website',
		skills: 'HTML | SCSS | Gulp',
        imgTab: '../image/projectsImg/tablet/img-10-tab.png',
		// img: project10,
		// imgTablet: projectTablet10,
		// imgMobile: projectMobile10,
		demoLink: 'https://desire-furniture-design.netlify.app/',
		gitLink: 'https://github.com/ArtemYakushkin/furniture-design/tree/main',
	},
	{
		id: 11,
		title: 'Landing site for Mercedes-Benz',
		skills: 'HTML | CSS',
        imgTab: '../image/projectsImg/tablet/img-11-tab.png',
		// img: project11,
		// imgTablet: projectTablet11,
		// imgMobile: projectMobile11,
		demoLink: 'https://artemyakushkin.github.io/mercedes-avatar/',
		gitLink: 'https://github.com/ArtemYakushkin/mercedes-avatar',
	},
	{
		id: 12,
		title: 'Barbershop landing site',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-12-tab.png',
		// img: project12,
		// imgTablet: projectTablet12,
		// imgMobile: projectMobile12,
		demoLink: 'https://artemyakushkin.github.io/barbershop/',
		gitLink: 'https://github.com/ArtemYakushkin/barbershop',
	},
	{
		id: 13,
		title: 'Landing site for web studio',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-13-tab.png',
		// img: project13,
		// imgTablet: projectTablet13,
		// imgMobile: projectMobile13,
		demoLink: 'https://artemyakushkin.github.io/WebStudio/index.html',
		gitLink: 'https://github.com/ArtemYakushkin/WebStudio',
	},
	{
		id: 14,
		title: 'Landing site for modern bakery',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-14-tab.png',
		// img: project14,
		// imgTablet: projectTablet14,
		// imgMobile: projectMobile14,
		demoLink: 'https://artemyakushkin.github.io/modern_bakery/',
		gitLink: 'https://github.com/ArtemYakushkin/modern_bakery',
	},
	{
		id: 15,
		title: 'Landing site for beauty saloon',
		skills: 'HTML | SCSS | JavaScript',
        imgTab: '../image/projectsImg/tablet/img-15-tab.png',
		// img: project15,
		// imgTablet: projectTablet15,
		// imgMobile: projectMobile15,
		demoLink: 'https://artemyakushkin.github.io/beauty_zone/',
		gitLink: 'https://github.com/ArtemYakushkin/beauty_zone',
	},
	{
		id: 16,
		title: 'Landing site for Bose',
		skills: 'HTML | SCSS',
        imgTab: '../image/projectsImg/tablet/img-16-tab.png',
		// img: project16,
		// imgTablet: projectTablet16,
		// imgMobile: projectMobile16,
		demoLink: 'https://artemyakushkin.github.io/bose/',
		gitLink: 'https://github.com/ArtemYakushkin/bose',
	},
];

const sliderContainer = document.querySelector('.project__carousel');
const card = createGalletyItem(projectsData);

sliderContainer.insertAdjacentHTML('beforeend', card);

function createGalletyItem(projectsData) {
    return projectsData.map(({ imgTab }) => {
        return `
            <li class="project__card">
                <div class="project__img">
                    <img src="${imgTab}" alt="" draggable="false" />
                </div>
            </li>    
        `;
    }).join('');
}